version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cv-analyzer-stack"
s3_prefix = "cv-analyzer"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
resolve_s3 = true

[default.build]
[default.build.parameters]
cached = true
parallel = true
